<?php

namespace AppBundle\Repository;

/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository {

    /**
     * 
     * @param type $id
     */
    public function getById($id) {
        if ($id) {
            return $this->createQueryBuilder('a')
                            ->leftJoin('a.image', 'i')->addSelect('i')
                            ->leftJoin('a.comments', 'c')->addSelect('c')
                            ->leftJoin('a.tags', 't')->addSelect('t')
                            ->where('a.id = :id')
                            ->setParameter(':id', (int) $id)
                            ->orderBy('a.date', 'DESC')
                            ->getQuery()
                            ->getOneOrNullResult();
        }
        return null;
    }

    /**
     * 
     * @param type $id
     * @return array
     */
    public function getByTagId($id) {
        if ($id) {
            return $this->createQueryBuilder('a')
                            ->leftJoin('a.tags', 't')->addSelect('t')
                            ->where('a.id = :id')
                            ->setParameter(':id', (int) $id)
                            ->andWhere('a.publicate = :publicate')
                            ->setParameter(':publicate', 1)
                            ->orderBy('a.date', 'DESC')
                            ->getQuery()
                            ->getResult();
        }
        return null;
    }

    /**
     * @param int $limit
     * @return array|null
     */
    public function getLast($limit = 5) {
        if ((int) $limit) {
            return $this->createQueryBuilder('a')
                            ->where('a.publicate = :publicate')
                            ->setParameter(':publicate', 1)
                            ->orderBy('a.date', 'DESC')
                            ->setMaxResults($limit)
                            ->getQuery()
                            ->getResult();
        }
        return null;
    }

    /**
     * @param int $limit
     * @return array|null
     */
    public function getYears($limit = 5) {
        if ((int) $limit) {
            return $this->createQueryBuilder('a')
                ->select('SUBSTRING(a.date,1,4)')
                ->distinct()
                ->orderBy('a.date', 'DESC')
                ->setMaxResults($limit)
                ->getQuery()
                ->getResult();
        }
        return null;
    }

    /**
     * @param $year
     * @param int $limit
     * @return array|null
     */
    public function getByYear($year, $limit = 20) {
        if ((int) $limit) {
            return $this->createQueryBuilder('a')
                ->select('a.date')
                ->orderBy('a.date', 'DESC')
                ->setMaxResults($limit)
                ->getQuery()
                ->getResult();
        }
        return null;
    }
}
