hb_advertising:
    resource: "@HBAdvertisingBundle/Resources/config/routing.yml"
    prefix:   /

hb_advertising_advert:
    resource: "@HBAdvertisingBundle/Controller/AdvertisingController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    #prefix: /blog

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: "{_locale}"
    requirements:
        _locale: "fr|en"
    defaults : {_locale: "fr" }

#add_blog:
#    path:     /blog/add
#    defaults: { _controller: AppBundle:Blog:add }
