hb_advertising:
    resource: "@HBAdvertisingBundle/Resources/config/routing.yml"
    prefix:   /

hb_advertising_advert:
    resource: "@HBAdvertisingBundle/Controller/AdvertisingController.php"
    type:     annotation

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
#add_blog:
#    path:     /blog/add
#    defaults: { _controller: AppBundle:Blog:add }
