<?php

namespace HB\AdvertisingBundle\Repository;

/**
 * Advert_ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Advert_ImageRepository extends \Doctrine\ORM\EntityRepository
{
}
